config/routes.rb
Rails.application.routes.draw do
  resources :places do
    member do
      get :notify_querent
    end
  end
  resources :lines
  resources :appearances
  resources :positions
  resources :spreads
  resources :readings do
    member do
      put :complete
      put :make_private
      put :not_private
    end
  end
  resources :events do
    member do
      get :line_shift
    end
  end
  devise_for :readers
  devise_for :querents, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  get 'querents/:querent_id/readings' => 'readings#index', :as => 'querent_readings'
  get 'querents/revise' => 'querents#revise', :as => 'revise_querent'
  patch 'querents/redefine' => 'querents#redefine', :as => 'redefine_querent'
  
  get 'readers/revise' => 'readers#revise', :as => 'revise_reader'
  patch 'readers/redefine' => 'readers#redefine', :as => 'redefine_reader'
  resources :interpretations do
    member do
      get :rewrite
    end
  end
  resources :suits do
    resources :cards
    resources :decks
    resources :interpretations
    resources :readers
    member do
      get :card_names
    end
  end
  resources :cards do
    resources :interpretations
  end
  resources :decks do
    resources :cards
    resources :suits
    resources :interpretations
    resources :readers
  end
  resources :traditions do
    resources :decks
    resources :suits
    resources :cards
    resources :interpretations
  end
  resources :logistics
  
  resources :readers, :only => [:index, :edit, :update, :new] do
    collection do
      post :name
    end
    member do
      put :activate
      put :deactivate
    end
    resources :interpretations
  end
  
  get '/guildlines/dj' => 'logistics#dj_guildlines', :as => 'dj_guildline'
  get '/guildlines/reader' => 'logistics#reader_guildlines', :as => 'reader_guildline'
  
  get '/querents' => 'querents#index'
  patch '/querents/approve_avatar/:id' => 'querents#approve_avatar', :as => 'approve_avatar'

  root 'logistics#index'

  post 'add_me_to_mail_list' => 'mailing#add_name'
end

app/models/tradition.rb
class Tradition < ApplicationRecord
  has_many :decks
  has_many :spreads
  has_many :cards, -> { uniq }, :through => :decks
  has_many :suits, -> { uniq }, :through => :cards
  has_many :interpretations, -> { uniq }, :through => :cards
end

app/controllers/traditions_controller.rb
class TraditionsController < ApplicationController
  before_action :set_tradition, only: [:show, :edit, :update, :destroy]

  # GET /traditions
  # GET /traditions.json
  def index
    @traditions = Tradition.all
  end

  # GET /traditions/1
  # GET /traditions/1.json
  def show
  end

  # GET /traditions/new
  def new
    @tradition = Tradition.new
  end

  # GET /traditions/1/edit
  def edit
  end

  # POST /traditions
  # POST /traditions.json
  def create
    @tradition = Tradition.new(tradition_params)

    respond_to do |format|
      if @tradition.save
        format.html { redirect_to @tradition, notice: 'Tradition was created.' }
        format.json { render :show, status: :created, location: @tradition }
      else
        format.html { render :new }
        format.json { render json: @tradition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /traditions/1
  # PATCH/PUT /traditions/1.json
  def update
    respond_to do |format|
      if @tradition.update(tradition_params)
        format.html { redirect_to @tradition, notice: 'Tradition was updated.' }
        format.json { render :show, status: :ok, location: @tradition }
      else
        format.html { render :edit }
        format.json { render json: @tradition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /traditions/1
  # DELETE /traditions/1.json
  def destroy
    @tradition.destroy
    respond_to do |format|
      format.html { redirect_to traditions_url, notice: 'Tradition was destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tradition
      @tradition = Tradition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tradition_params
      params.require(:tradition).permit(:name)
    end
end

app/helpers/traditions_helper.rb
module TraditionsHelper
  def navigation_in_cards
    content_tag(:div, :id => 'getting_around') do
      content_tag(:div, :id => 'this_is_the_way') do
        'You may find these pathways useful'
      end +
      content_tag(:nav, :id => 'magician_navigation') do
        navigation_to_resource('traditions') +
        navigation_to_resource('decks') +
        navigation_to_resource('suits') +
        navigation_to_resource('cards') +
        navigation_to_resource('interpretations') +
        navigation_to_resource('spreads') +
        navigation_to_resource('positions') +
        navigation_to_resource('readers') +
        navigation_to_resource('events') +
        navigation_to_resource('readings') +
        navigation_to_resource('positions') +
        navigation_to_resource('appearances') +
        navigation_to_resource('lines') +
        navigation_to_resource('places')
      end
    end
  end
  
  def navigation_for_reader
    content_tag(:div, :id => 'getting_around') do
      content_tag(:div, :id => 'this_is_the_way') do
        'You may find these pathways useful'
      end +
      content_tag(:nav, :id => 'magician_navigation') do
        navigation_to_resource('decks') +
        navigation_to_resource('spreads') +
        navigation_to_resource('events') +
        navigation_to_resource('readings') +
        navigation_to_resource('interpretations')
      end
    end
  end
  
  def navigation_for_querent
    content_tag(:div, :id => 'getting_around') do
      content_tag(:div, :id => 'this_is_the_way') do
        'You may find these pathways useful'
      end +
      content_tag(:nav, :id => 'magician_navigation') do
        link_to('See queues, get a reading', Event.last) + '&nbsp;&nbsp;&nbsp;&nbsp;'.html_safe +
        link_to('Review my readings', querent_readings_path(current_querent))
      end
    end
  end
  
  def navigation_to_resource canopy
    content_tag :li, :id => canopy do
      link_to canopy, send("#{canopy}_path")
    end
  end
end

app/views/traditions/_form.html.erb
<%= form_for(@tradition) do |f| %>
  <% if @tradition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tradition.errors.count, "error") %> prohibited this tradition from being saved:</h2>

      <ul>
      <% @tradition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/traditions/edit.html.erb
<h1>interfering with Tradition</h1>

<%= render 'form' %>

<%= link_to 'inspect->/', @tradition %> |
<%= link_to 'Back', traditions_path %>

app/views/traditions/index.html.erb
<h1>a List of Traditions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @traditions.each do |tradition| %>
      <tr>
        <td><%= tradition.name %></td>
        <td><%= plural_nest tradition, 'deck' %></td>
        <td><%= plural_nest tradition, 'card' %></td>
        <td><%= plural_nest tradition, 'suit' %></td>
        <td><%= plural_nest tradition, 'interpretation' %></td>
        <td><%= link_to 'inspect->/', tradition %></td>
        <td><%= link_to 'interfere', edit_tradition_path(tradition) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tradition', new_tradition_path %>

app/views/traditions/new.html.erb
<h1>New Tradition</h1>

<%= render 'form' %>

<%= link_to 'Back', traditions_path %>

app/views/traditions/show.html.erb
<p>
  <%= @tradition.name %>
</p>

<%= content_tag_for :header, @tradition, :decks do %>
  ~decks~
<% end %>
<%= div_for @tradition, :decks_for do %>
  <% @tradition.decks.each do |deck| %>
    <%= div_for deck do %>
      <%= link_to deck.name, deck %>
    <% end %>
  <% end %>
<% end %>

<%= content_tag_for :header, @tradition, :spreads do %>
  ~spreads~
<% end %>
<%= div_for @tradition, :spreads_for do %>
  <% @tradition.spreads.each do |spread| %>
    <%= div_for spread do %>
      <%= link_to spread.name, spread %>
    <% end %>
  <% end %>
<% end %>