config/routes.rb
Rails.application.routes.draw do
  resources :places do
    member do
      get :notify_querent
    end
  end
  resources :lines
  resources :appearances
  resources :positions
  resources :spreads
  resources :readings do
    member do
      put :complete
      put :make_private
      put :not_private
    end
  end
  resources :events do
    member do
      get :line_shift
    end
  end
  devise_for :readers
  devise_for :querents, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  get 'querents/:querent_id/readings' => 'readings#index', :as => 'querent_readings'
  get 'querents/revise' => 'querents#revise', :as => 'revise_querent'
  patch 'querents/redefine' => 'querents#redefine', :as => 'redefine_querent'
  
  get 'readers/revise' => 'readers#revise', :as => 'revise_reader'
  patch 'readers/redefine' => 'readers#redefine', :as => 'redefine_reader'
  resources :interpretations do
    member do
      get :rewrite
    end
  end
  resources :suits do
    resources :cards
    resources :decks
    resources :interpretations
    resources :readers
    member do
      get :card_names
    end
  end
  resources :cards do
    resources :interpretations
  end
  resources :decks do
    resources :cards
    resources :suits
    resources :interpretations
    resources :readers
  end
  resources :traditions do
    resources :decks
    resources :suits
    resources :cards
    resources :interpretations
  end
  resources :logistics
  
  resources :readers, :only => [:index, :edit, :update, :new] do
    collection do
      post :name
    end
    member do
      put :activate
      put :deactivate
    end
    resources :interpretations
  end
  
  get '/guildlines/dj' => 'logistics#dj_guildlines', :as => 'dj_guildline'
  get '/guildlines/reader' => 'logistics#reader_guildlines', :as => 'reader_guildline'
  
  get '/querents' => 'querents#index'
  patch '/querents/approve_avatar/:id' => 'querents#approve_avatar', :as => 'approve_avatar'

  root 'logistics#index'

  post 'add_me_to_mail_list' => 'mailing#add_name'
end

app/models/suit.rb
class Suit < ApplicationRecord
  extend CriticalPath
  has_many :cards
  has_many :decks, -> { uniq }, :through => :cards
  has_many :suits, -> { uniq }, :through => :cards
  has_many :interpretations, -> { uniq }, :through => :cards
  has_many :readers, -> { uniq }, :through => :interpretations
  
  scope :regarding_tradition, lambda { |tradition| joins(:decks).where 'decks.tradition_id' => tradition }
  scope :regarding_deck, lambda { |deck| joins(:cards).where 'cards.deck_id' => deck }
  scope :regarding_reader, lambda { |reader| joins(:interpretations).where 'interpretations.reader_id' => reader }
end

app/controllers/suits_controller.rb
class SuitsController < ApplicationController
  before_action :set_suit, only: [:show, :edit, :update, :destroy, :card_names]

  # GET /suits
  # GET /suits.json
  def index
    @suits = Suit.select_with_criteria params, :tradition, :deck, :reader
  end

  # GET /suits/1
  # GET /suits/1.json
  def show
  end
  
  def card_names
    @cards = @suit.cards
  end

  # GET /suits/new
  def new
    @suit = Suit.new
  end

  # GET /suits/1/edit
  def edit
  end

  # POST /suits
  # POST /suits.json
  def create
    @suit = Suit.new(suit_params)

    respond_to do |format|
      if @suit.save
        format.html { redirect_to @suit, notice: 'Suit was created.' }
        format.json { render :show, status: :created, location: @suit }
      else
        format.html { render :new }
        format.json { render json: @suit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suits/1
  # PATCH/PUT /suits/1.json
  def update
    respond_to do |format|
      if @suit.update(suit_params)
        format.html { redirect_to @suit, notice: 'Suit was updated.' }
        format.json { render :show, status: :ok, location: @suit }
      else
        format.html { render :edit }
        format.json { render json: @suit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suits/1
  # DELETE /suits/1.json
  def destroy
    @suit.destroy
    respond_to do |format|
      format.html { redirect_to suits_url, notice: 'Suit was destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suit
      @suit = Suit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def suit_params
      params.require(:suit).permit(:name, :symbol)
    end
end

app/helpers/suits_helper.rb
module SuitsHelper
end

app/views/suits/_form.html.erb
<%= form_for(@suit) do |f| %>
  <% if @suit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@suit.errors.count, "error") %> prohibited this suit from being saved:</h2>

      <ul>
      <% @suit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suits/card_names.html.erb
<% @cards.each do |card| %>
  <%= card.interpretations.last.try(:phrase) %>
<% end %>

app/views/suits/edit.html.erb
<h1>interfering with Suit</h1>

<%= render 'form' %>

<%= link_to 'inspect->/', @suit %> |
<%= link_to 'Back', suits_path %>

app/views/suits/index.html.erb
<h1>a List of Suits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @suits.each do |suit| %>
      <tr>
        <td><%= suit.name %></td>
        <td><%= suit.symbol %></td>
        <td><%= plural_nest suit, 'card' %></td>
        <td><%= plural_nest suit, 'deck' %></td>
        <td><%= plural_nest suit, 'interpretation' %></td>
        <td><%= plural_nest suit, 'reader' %></td>
        <td><%= link_to 'inspect->/', suit %></td>
        <td><%= link_to 'interfere', edit_suit_path(suit) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Suit', new_suit_path %>

app/views/suits/new.html.erb
<h1>New Suit</h1>

<%= render 'form' %>

<%= link_to 'Back', suits_path %>

app/views/suits/show.html.erb
<%= link_to 'card names', card_names_suit_path(@suit) %>

<p>
  <%= @suit.name %>
</p>

<p>
  <strong>Symbol:</strong>
  <%= @suit.symbol %>
</p>

<%= link_to 'interfere', edit_suit_path(@suit) %> |
<%= link_to 'Back', suits_path %>