config/routes.rb
Rails.application.routes.draw do
  resources :places do
    member do
      get :notify_querent
    end
  end
  resources :lines
  resources :appearances
  resources :positions
  resources :spreads
  resources :readings do
    member do
      put :complete
      put :make_private
      put :not_private
    end
  end
  resources :events do
    member do
      get :line_shift
    end
  end
  devise_for :readers
  devise_for :querents, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  get 'querents/:querent_id/readings' => 'readings#index', :as => 'querent_readings'
  get 'querents/revise' => 'querents#revise', :as => 'revise_querent'
  patch 'querents/redefine' => 'querents#redefine', :as => 'redefine_querent'
  
  get 'readers/revise' => 'readers#revise', :as => 'revise_reader'
  patch 'readers/redefine' => 'readers#redefine', :as => 'redefine_reader'
  resources :interpretations do
    member do
      get :rewrite
    end
  end
  resources :suits do
    resources :cards
    resources :decks
    resources :interpretations
    resources :readers
    member do
      get :card_names
    end
  end
  resources :cards do
    resources :interpretations
  end
  resources :decks do
    resources :cards
    resources :suits
    resources :interpretations
    resources :readers
  end
  resources :traditions do
    resources :decks
    resources :suits
    resources :cards
    resources :interpretations
  end
  resources :logistics
  
  resources :readers, :only => [:index, :edit, :update, :new] do
    collection do
      post :name
    end
    member do
      put :activate
      put :deactivate
    end
    resources :interpretations
  end
  
  get '/guildlines/dj' => 'logistics#dj_guildlines', :as => 'dj_guildline'
  get '/guildlines/reader' => 'logistics#reader_guildlines', :as => 'reader_guildline'
  
  get '/querents' => 'querents#index'
  patch '/querents/approve_avatar/:id' => 'querents#approve_avatar', :as => 'approve_avatar'

  root 'logistics#index'

  post 'add_me_to_mail_list' => 'mailing#add_name'
end

app/models/interpretation.rb
class Interpretation < ApplicationRecord
  extend CriticalPath
  belongs_to :card
  belongs_to :appearance
  has_one :reading, :through => :appearance
  belongs_to :reader
  
  scope :regarding_suit, lambda { |suit| joins(:card).where 'cards.suit_id' => suit }
  scope :regarding_card, lambda { |card| where :card_id => card }
  scope :regarding_reader, lambda { |reader| where :reader_id => reader }
  scope :private_reading, lambda { joins(:reading).where('readings.private' => true) }
  scope :not_private_reading, lambda { joins(:reading).where('readings.private' => false) }
  
  def reader_moniker
    reader.try :moniker
  end
end

app/controllers/interpretations_controller.rb
class InterpretationsController < ApplicationController
  before_action :set_interpretation, only: [:show, :rewrite, :edit, :update, :destroy]

  # GET /interpretations
  # GET /interpretations.json
  def index
    @interpretations = Interpretation.select_with_criteria(params, :suit, :card, :reader)
  end

  # GET /interpretations/1
  # GET /interpretations/1.json
  def show
  end

  # GET /interpretations/new
  def new
    @interpretation = Interpretation.new
  end
  
  def rewrite
  end

  # GET /interpretations/1/edit
  def edit
  end

  # POST /interpretations
  # POST /interpretations.json
  def create
    @interpretation = Interpretation.new(interpretation_params)

    respond_to do |format|
      if @interpretation.save
        format.html { redirect_to @interpretation, notice: 'Interpretation was created.' }
        format.js
        format.json { render :show, status: :created, location: @interpretation }
      else
        format.html { render :new }
        format.json { render json: @interpretation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interpretations/1
  # PATCH/PUT /interpretations/1.json
  def update
    respond_to do |format|
      if @interpretation.update(interpretation_params)
        format.html { redirect_to @interpretation, notice: 'Interpretation was updated.' }
        format.json { render :show, status: :ok, location: @interpretation }
      else
        format.html { render :edit }
        format.json { render json: @interpretation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interpretations/1
  # DELETE /interpretations/1.json
  def destroy
    @interpretation.destroy
    respond_to do |format|
      format.html { redirect_to interpretations_url, notice: 'Interpretation was destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interpretation
      @interpretation = Interpretation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interpretation_params
      params.require(:interpretation).permit(:card_id, :appearance_id, :phrase, :description, :reader_id)
    end
end

app/helpers/interpretations_helper.rb
module InterpretationsHelper
  def appearance_interpretation_form appearance
    form_for appearance.interpretations.new, :remote => true, :html => {:id => dom_id(appearance, :interpretation_of)} do |interpretation_form|
      interpretation_form.text_field(:phrase, :placeholder => 'phrase') +
      interpretation_form.text_area(:description, :placeholder => 'explanation') +
      interpretation_form.submit('enter interpretation') +
      interpretation_form.hidden_field(:appearance_id, :value => appearance.id) +
      interpretation_form.hidden_field(:card_id, :value => appearance.card_id) +
      interpretation_form.hidden_field(:reader_id, :value => appearance.reader.id)
    end
  end
  
  def interpretation_display interpretation
    content_tag_for(:header, interpretation) do
      interpretation.phrase
    end +
    div_for(interpretation) do
      interpretation.description
    end
  end
end

app/views/interpretations/_form.html.erb
<%= form_for(@interpretation) do |f| %>
  <% if @interpretation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interpretation.errors.count, "error") %> prohibited this interpretation from being saved:</h2>

      <ul>
      <% @interpretation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :card_id %><br>
    <%= f.select :card_id, options_from_collection_for_select(Card.all, :id, :name, @interpretation.card_id) %>
  </div>
  <div class="field">
    <%= f.label :appearance_id %><br>
    <%= f.select :appearance_id, options_from_collection_for_select(Appearance.all, :id, :name, @interpretation.appearance_id), :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :phrase %><br>
    <%= f.text_field :phrase %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :reader_id %><br>
    <%= f.select :reader_id, options_from_collection_for_select(Reader.all, :id, :moniker, @interpretation.reader_id) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interpretations/create.js.erb
$('#<%= dom_id(@interpretation.appearance, :interpretation_of) %>').replaceWith('<%= escape_javascript interpretation_display(@interpretation) %>');

app/views/interpretations/edit.html.erb
<h1>interfering with Interpretation</h1>

<%= render 'form' %>

<%= link_to 'inspect->/', @interpretation %> |
<%= link_to 'Back', interpretations_path %>

app/views/interpretations/index.html.erb
<h1>a List of Interpretations</h1>

<table>
  <thead>
    <tr>
      <th>Card</th>
      <th>Phrase</th>
      <th>Description</th>
      <th>Reading</th>
      <th>Reader</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interpretations.each do |interpretation| %>
      <tr>
        <td><%= interpretation.card.name %></td>
        <td><%= interpretation.phrase %></td>
        <td><%= markdowner.render(interpretation.description).html_safe %></td>
        <td><%= interpretation.appearance.try(:name) %></td>
        <td><%= interpretation.reader.name %></td>
        <td><%= link_to 'inspect->/', interpretation %></td>
        <td><%= link_to 're-write', rewrite_interpretation_path(interpretation) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interpretation', new_interpretation_path %>

app/views/interpretations/new.html.erb
<h1>New Interpretation</h1>

<%= render 'form' %>

<%= link_to 'Back', interpretations_path %>

app/views/interpretations/rewrite.html.erb
<%= div_for @interpretation, :existing_name_of do %>
  <%= @interpretation.phrase %>
<% end %>

<%= div_for @interpretation, :existing_text_of do %>
  <%= @interpretation.description %>
<% end %>

<div>
  <strong>
    <%= @interpretation.card.name %>
  </strong>
</div>

<%= form_for Interpretation.new(card_id: @interpretation.card_id) do |f| %>
  <%= f.hidden_field :card_id %>
  <%= f.text_field :phrase, :placeholder => 'phrase' %>
  <br>
  <%= f.text_area :description, :placeholder => 'description' %>
  <br>
  <%= f.submit "Reinterpreted!" %>
  <%= f.hidden_field :reader_id, value: current_reader.id %>
<% end %>

app/views/interpretations/show.html.erb
<p>
  <strong>Card:</strong>
  <%= @interpretation.card.name %>
</p>

<p>
  <strong>Phrase:</strong>
  <%= @interpretation.phrase %>
</p>

<p>
  <strong>Description:</strong>
  <%= markdowner.render(@interpretation.description).html_safe %>
</p>

<p>
  <strong>Reader:</strong>
  <%= @interpretation.reader.moniker %>
</p>

<%= link_to 'interfere', edit_interpretation_path(@interpretation) %> |
<%= link_to 'Back', interpretations_path %>