config/routes.rb
Rails.application.routes.draw do
  resources :places do
    member do
      get :notify_querent
    end
  end
  resources :lines
  resources :appearances
  resources :positions
  resources :spreads
  resources :readings do
    member do
      put :complete
      put :make_private
      put :not_private
    end
  end
  resources :events do
    member do
      get :line_shift
    end
  end
  devise_for :readers
  devise_for :querents, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  get 'querents/:querent_id/readings' => 'readings#index', :as => 'querent_readings'
  get 'querents/revise' => 'querents#revise', :as => 'revise_querent'
  patch 'querents/redefine' => 'querents#redefine', :as => 'redefine_querent'
  
  get 'readers/revise' => 'readers#revise', :as => 'revise_reader'
  patch 'readers/redefine' => 'readers#redefine', :as => 'redefine_reader'
  resources :interpretations do
    member do
      get :rewrite
    end
  end
  resources :suits do
    resources :cards
    resources :decks
    resources :interpretations
    resources :readers
    member do
      get :card_names
    end
  end
  resources :cards do
    resources :interpretations
  end
  resources :decks do
    resources :cards
    resources :suits
    resources :interpretations
    resources :readers
  end
  resources :traditions do
    resources :decks
    resources :suits
    resources :cards
    resources :interpretations
  end
  resources :logistics
  
  resources :readers, :only => [:index, :edit, :update, :new] do
    collection do
      post :name
    end
    member do
      put :activate
      put :deactivate
    end
    resources :interpretations
  end
  
  get '/guildlines/dj' => 'logistics#dj_guildlines', :as => 'dj_guildline'
  get '/guildlines/reader' => 'logistics#reader_guildlines', :as => 'reader_guildline'
  
  get '/querents' => 'querents#index'
  patch '/querents/approve_avatar/:id' => 'querents#approve_avatar', :as => 'approve_avatar'

  root 'logistics#index'

  post 'add_me_to_mail_list' => 'mailing#add_name'
end

app/models/deck.rb
class Deck < ApplicationRecord
  extend CriticalPath
  belongs_to :tradition
  has_many :cards, -> { uniq }
  has_many :suits, -> { uniq }, :through => :cards
  has_many :interpretations, -> { uniq }, :through => :cards
  has_many :readers, -> { uniq }, :through => :interpretations
  has_many :readings
  
  scope :alphabetical, lambda { order(:name) }
  scope :regarding_tradition, lambda { |tradition| where :tradition_id => tradition }
  scope :regarding_suit, lambda { |suit| joins(:cards).where 'cards.suit_id' => suit }
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy]

  # GET /decks
  # GET /decks.json
  def index
    @decks = Deck.select_with_criteria(params, :tradition, :suit)
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
  end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(deck_params)

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was created.' }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'Deck was updated.' }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url, notice: 'Deck was destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = Deck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deck_params
      params.require(:deck).permit(:tradition_id, :name)
    end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/decks/_form.html.erb
<%= form_for(@deck) do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tradition_id %><br>
    <%= f.select :tradition_id, options_from_collection_for_select(Tradition.all, :id, :name, @deck.tradition_id) %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<h1>interfering with Deck</h1>

<%= render 'form' %>

<%= link_to 'inspect->/', @deck %> |
<%= link_to 'Back', decks_path %>

app/views/decks/index.html.erb
<h1>these are the decks we know</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tradition</th>
    </tr>
  </thead>

  <tbody>
    <% @decks.each do |deck| %>
      <tr>
        <td><%= link_to deck.name, deck %></td>
        <td><%= deck.tradition.name %></td>
        <td><%= plural_nest deck, 'suit' %></td>
        <td><%= plural_nest deck, 'card' %></td>
        <td><%= plural_nest deck, 'interpretation' %></td>
        <td><%= plural_nest deck, 'reader' %></td>
        <td><%= link_to 'inspect->/', deck %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deck', new_deck_path %>

app/views/decks/new.html.erb
<h1>New Deck</h1>

<%= render 'form' %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<p>
  <strong>Tradition:</strong>
  <%= link_to @deck.tradition.name, @deck.tradition %>
</p>

<p>
  <%= @deck.name %>
</p>

<%= content_tag_for :header, @deck, :cards do %>
  ~cards~
<% end %>
<%= div_for @deck, :cards_in do %>
  <% @deck.cards.sequenced.each do |card| %>
    <%= div_for card do %>
      <%= link_to card.name, card %>
    <% end %>
  <% end %>
<% end %>

<%= div_for @deck, :card_adder_for do %>
  <%= link_to 'Add Card', new_card_path(:card => {:deck_id => @deck.id}), :remote => true %>
<% end %>